name: Upload Python Package

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.x'
    - name : Get Release Version
      id: get_version
      run : echo ::set-output name=VERSION::$(echo $(echo $(grep "__version__" mlcf/__init__.py)) | cut -d'=' -f2)
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ steps.get_version.outputs.VERSION }}
        message: ${{ steps.get_version.outputs.VERSION }} release
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}