name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.x'
    - name : Auto-increment version
      run : |
        VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
        VERSION_FILE='mlcf/__init__.py'
        PLACEHOLDER=$(echo $(grep "__version__" "$VERSION_FILE"))
        grep "$PLACEHOLDER" "$VERSION_FILE"
        sed -i "s/$PLACEHOLDER/__version__ = \"${VERSION}\"/g" "$VERSION_FILE"
      shell: bash
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Commit Auto-increment
      uses: actions-js/push@master
      with:
        author_name: "GithubActionBot"
        message: "Auto-increment version to ${{ steps.get_version.outputs.VERSION }}"
        github_token: ${{ secrets.MLCF_GITREPO_TOKEN }}
        branch: "main"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}