name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name : Auto-increment version
      run : |
        VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
        PLACEHOLDER=$(echo $(grep "__version__" "$VERSION_FILE"))
        VERSION_FILE='mlcf/__init__.py'
        grep "$PLACEHOLDER" "$VERSION_FILE"
        sed -i "s/$PLACEHOLDER/__version__ = \"${VERSION}\"/g" "$VERSION_FILE"
      shell: bash
    - name: Commit Auto-increment
      uses: EndBug/add-and-commit@v8.0.2
      with:
        committer_name: "Github Action"
        message: "Auto-increment version to ${{ github.ref }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}